import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Cogito",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head />
			<body className="flex flex-col min-h-screen">
				<Navbar />
				<div>
					<Hero />
				</div>
				<div className="flex flex-1">
					<main className="flex-1 p-4">{children}</main>
				</div>
			</body>
		</html>
	);
}
